# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(934, 729)
        self.centralwidget = QtWidgets.QWidget(MainForm)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 941, 731))
        self.tabWidget.setObjectName("tabWidget")
        self.tabSetup = QtWidgets.QWidget()
        self.tabSetup.setObjectName("tabSetup")
        self.groupData = QtWidgets.QGroupBox(self.tabSetup)
        self.groupData.setGeometry(QtCore.QRect(0, 0, 461, 691))
        self.groupData.setObjectName("groupData")
        self.groupBox = QtWidgets.QGroupBox(self.groupData)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 441, 471))
        self.groupBox.setObjectName("groupBox")
        self.comboDataset = QtWidgets.QComboBox(self.groupBox)
        self.comboDataset.setGeometry(QtCore.QRect(145, 40, 281, 26))
        self.comboDataset.setObjectName("comboDataset")
        self.comboDataset.addItem("")
        self.comboDataset.addItem("")
        self.comboDataset.addItem("")
        self.comboDataset.addItem("")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 40, 131, 31))
        self.label_15.setObjectName("label_15")
        self.widgetDataset = QtWidgets.QWidget(self.groupBox)
        self.widgetDataset.setGeometry(QtCore.QRect(10, 80, 421, 381))
        self.widgetDataset.setObjectName("widgetDataset")
        self.groupModel = QtWidgets.QGroupBox(self.tabSetup)
        self.groupModel.setGeometry(QtCore.QRect(470, 0, 461, 691))
        self.groupModel.setObjectName("groupModel")
        self.comboModel = QtWidgets.QComboBox(self.groupModel)
        self.comboModel.setGeometry(QtCore.QRect(165, 30, 231, 26))
        self.comboModel.setObjectName("comboModel")
        self.comboModel.addItem("")
        self.comboModel.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupModel)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupModel)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 140, 31))
        self.label_9.setObjectName("label_9")
        self.comboOptimizer = QtWidgets.QComboBox(self.groupModel)
        self.comboOptimizer.setGeometry(QtCore.QRect(165, 70, 231, 26))
        self.comboOptimizer.setObjectName("comboOptimizer")
        self.comboOptimizer.addItem("")
        self.comboOptimizer.addItem("")
        self.comboOptimizer.addItem("")
        self.comboOptimizer.addItem("")
        self.comboOptimizer.addItem("")
        self.label_10 = QtWidgets.QLabel(self.groupModel)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 141, 31))
        self.label_10.setObjectName("label_10")
        self.comboLoss = QtWidgets.QComboBox(self.groupModel)
        self.comboLoss.setGeometry(QtCore.QRect(165, 110, 231, 26))
        self.comboLoss.setObjectName("comboLoss")
        self.comboLoss.addItem("")
        self.plainOptimizer = QtWidgets.QPlainTextEdit(self.groupModel)
        self.plainOptimizer.setGeometry(QtCore.QRect(10, 280, 441, 64))
        self.plainOptimizer.setPlainText("")
        self.plainOptimizer.setObjectName("plainOptimizer")
        self.label_11 = QtWidgets.QLabel(self.groupModel)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 441, 31))
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupModel)
        self.label_12.setGeometry(QtCore.QRect(10, 350, 441, 31))
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12.setObjectName("label_12")
        self.plainLoss = QtWidgets.QPlainTextEdit(self.groupModel)
        self.plainLoss.setGeometry(QtCore.QRect(10, 380, 441, 64))
        self.plainLoss.setReadOnly(False)
        self.plainLoss.setObjectName("plainLoss")
        self.label_13 = QtWidgets.QLabel(self.groupModel)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 441, 31))
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_13.setObjectName("label_13")
        self.plainModel = QtWidgets.QPlainTextEdit(self.groupModel)
        self.plainModel.setGeometry(QtCore.QRect(10, 180, 441, 64))
        self.plainModel.setReadOnly(False)
        self.plainModel.setObjectName("plainModel")
        self.tabWidget.addTab(self.tabSetup, "")
        self.tabTrain = QtWidgets.QWidget()
        self.tabTrain.setObjectName("tabTrain")
        self.groupTrain = QtWidgets.QGroupBox(self.tabTrain)
        self.groupTrain.setGeometry(QtCore.QRect(0, 0, 271, 691))
        self.groupTrain.setObjectName("groupTrain")
        self.label = QtWidgets.QLabel(self.groupTrain)
        self.label.setGeometry(QtCore.QRect(10, 40, 111, 31))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.spinEpochLimit = QtWidgets.QSpinBox(self.groupTrain)
        self.spinEpochLimit.setGeometry(QtCore.QRect(130, 40, 131, 30))
        self.spinEpochLimit.setMaximum(200000)
        self.spinEpochLimit.setSingleStep(100)
        self.spinEpochLimit.setProperty("value", 200)
        self.spinEpochLimit.setObjectName("spinEpochLimit")
        self.label_2 = QtWidgets.QLabel(self.groupTrain)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 131, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.spinLearningRate = QtWidgets.QDoubleSpinBox(self.groupTrain)
        self.spinLearningRate.setGeometry(QtCore.QRect(140, 80, 121, 30))
        self.spinLearningRate.setDecimals(5)
        self.spinLearningRate.setMinimum(1e-05)
        self.spinLearningRate.setMaximum(2.0)
        self.spinLearningRate.setSingleStep(0.001)
        self.spinLearningRate.setObjectName("spinLearningRate")
        self.label_3 = QtWidgets.QLabel(self.groupTrain)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 131, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.spinSatisLoss = QtWidgets.QDoubleSpinBox(self.groupTrain)
        self.spinSatisLoss.setGeometry(QtCore.QRect(140, 120, 121, 30))
        self.spinSatisLoss.setDecimals(5)
        self.spinSatisLoss.setMinimum(1e-05)
        self.spinSatisLoss.setMaximum(2.0)
        self.spinSatisLoss.setSingleStep(0.001)
        self.spinSatisLoss.setObjectName("spinSatisLoss")
        self.label_4 = QtWidgets.QLabel(self.groupTrain)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 131, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.spinMinDLoss = QtWidgets.QDoubleSpinBox(self.groupTrain)
        self.spinMinDLoss.setGeometry(QtCore.QRect(140, 160, 121, 30))
        self.spinMinDLoss.setDecimals(5)
        self.spinMinDLoss.setMinimum(1e-05)
        self.spinMinDLoss.setMaximum(2.0)
        self.spinMinDLoss.setSingleStep(0.001)
        self.spinMinDLoss.setProperty("value", 1e-05)
        self.spinMinDLoss.setObjectName("spinMinDLoss")
        self.checkHotStart = QtWidgets.QCheckBox(self.groupTrain)
        self.checkHotStart.setGeometry(QtCore.QRect(10, 370, 131, 31))
        self.checkHotStart.setCheckable(False)
        self.checkHotStart.setObjectName("checkHotStart")
        self.buttonFit = QtWidgets.QPushButton(self.groupTrain)
        self.buttonFit.setGeometry(QtCore.QRect(130, 370, 131, 30))
        self.buttonFit.setObjectName("buttonFit")
        self.plainFit = QtWidgets.QPlainTextEdit(self.groupTrain)
        self.plainFit.setGeometry(QtCore.QRect(10, 230, 251, 131))
        self.plainFit.setObjectName("plainFit")
        self.label_14 = QtWidgets.QLabel(self.groupTrain)
        self.label_14.setGeometry(QtCore.QRect(10, 200, 251, 31))
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_14.setObjectName("label_14")
        self.widgetLoss = QtWidgets.QWidget(self.groupTrain)
        self.widgetLoss.setGeometry(QtCore.QRect(10, 460, 251, 221))
        self.widgetLoss.setObjectName("widgetLoss")
        self.spinLossHistory = QtWidgets.QSpinBox(self.groupTrain)
        self.spinLossHistory.setGeometry(QtCore.QRect(130, 410, 131, 30))
        self.spinLossHistory.setMaximum(200000)
        self.spinLossHistory.setSingleStep(10)
        self.spinLossHistory.setObjectName("spinLossHistory")
        self.buttonLossHist = QtWidgets.QPushButton(self.groupTrain)
        self.buttonLossHist.setGeometry(QtCore.QRect(14, 410, 111, 30))
        self.buttonLossHist.setObjectName("buttonLossHist")
        self.groupResult = QtWidgets.QGroupBox(self.tabTrain)
        self.groupResult.setGeometry(QtCore.QRect(280, 0, 651, 691))
        self.groupResult.setObjectName("groupResult")
        self.widgetResults = QtWidgets.QWidget(self.groupResult)
        self.widgetResults.setGeometry(QtCore.QRect(9, 29, 631, 651))
        self.widgetResults.setObjectName("widgetResults")
        self.tabWidget.addTab(self.tabTrain, "")
        MainForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Super Mega ML"))
        self.groupData.setTitle(_translate("MainForm", "Data Parameters"))
        self.groupBox.setTitle(_translate("MainForm", "Internal Datasets"))
        self.comboDataset.setItemText(0, _translate("MainForm", "Linear 2D with noise"))
        self.comboDataset.setItemText(1, _translate("MainForm", "\"Fish\" 2D"))
        self.comboDataset.setItemText(2, _translate("MainForm", "Linear 3D with noise"))
        self.comboDataset.setItemText(3, _translate("MainForm", "\"Fish\" 3D"))
        self.label_15.setText(_translate("MainForm", "Dataset"))
        self.groupModel.setTitle(_translate("MainForm", "Model Parameters"))
        self.comboModel.setItemText(0, _translate("MainForm", "Linear Regression"))
        self.comboModel.setItemText(1, _translate("MainForm", "Random"))
        self.label_8.setText(_translate("MainForm", "Model"))
        self.label_9.setText(_translate("MainForm", "Optimizer"))
        self.comboOptimizer.setItemText(0, _translate("MainForm", "Gradient"))
        self.comboOptimizer.setItemText(1, _translate("MainForm", "SGD"))
        self.comboOptimizer.setItemText(2, _translate("MainForm", "MomentGrad"))
        self.comboOptimizer.setItemText(3, _translate("MainForm", "NesterovGrad"))
        self.comboOptimizer.setItemText(4, _translate("MainForm", "MyGrad"))
        self.label_10.setText(_translate("MainForm", "Loss Function"))
        self.comboLoss.setItemText(0, _translate("MainForm", "Linear MSE"))
        self.label_11.setText(_translate("MainForm", "Optimizer Options"))
        self.label_12.setText(_translate("MainForm", "Loss Options"))
        self.label_13.setText(_translate("MainForm", "Model Options"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSetup), _translate("MainForm", "Setup"))
        self.groupTrain.setTitle(_translate("MainForm", "Training"))
        self.label.setText(_translate("MainForm", "Epoch Limit"))
        self.label_2.setText(_translate("MainForm", "Learning Rate"))
        self.label_3.setText(_translate("MainForm", "Satis. Loss"))
        self.label_4.setText(_translate("MainForm", "Minimal DLoss"))
        self.checkHotStart.setText(_translate("MainForm", "Hot Start"))
        self.buttonFit.setText(_translate("MainForm", "Fit"))
        self.label_14.setText(_translate("MainForm", "Fit Parameters"))
        self.buttonLossHist.setText(_translate("MainForm", "View last:"))
        self.groupResult.setTitle(_translate("MainForm", "Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTrain), _translate("MainForm", "Training"))

